/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const card: string;
declare const title: string;
declare const description: string;
declare const button: string;
declare const demoButton: string;
declare const githubButton: string;

export {
	card,
	title,
	description,
	button,
	demoButton,
	githubButton
};

declare const __default_export__: {
	card: typeof card;
	title: typeof title;
	description: typeof description;
	button: typeof button;
	demoButton: typeof demoButton;
	githubButton: typeof githubButton;
};
export default __default_export__;
