/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const headerContainer: string;
declare const container: string;
declare const nav: string;
declare const logo: string;
declare const links: string;
declare const social: string;
declare const socialLink: string;

export {
	header,
	headerContainer,
	container,
	nav,
	logo,
	links,
	social,
	socialLink
};

declare const __default_export__: {
	header: typeof header;
	headerContainer: typeof headerContainer;
	container: typeof container;
	nav: typeof nav;
	logo: typeof logo;
	links: typeof links;
	social: typeof social;
	socialLink: typeof socialLink;
};
export default __default_export__;
