/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const social: string;
declare const socialLink: string;

export {
	social,
	socialLink
};

declare const __default_export__: {
	social: typeof social;
	socialLink: typeof socialLink;
};
export default __default_export__;
