/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const logo: string;

export {
	logo
};

declare const __default_export__: {
	logo: typeof logo;
};
export default __default_export__;
