/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const item: string;

export {
	item
};

declare const __default_export__: {
	item: typeof item;
};
export default __default_export__;
