/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const navigation: string;
declare const item: string;

export {
	navigation,
	item
};

declare const __default_export__: {
	navigation: typeof navigation;
	item: typeof item;
};
export default __default_export__;
