/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const section: string;

export {
	section
};

declare const __default_export__: {
	section: typeof section;
};
export default __default_export__;
