/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const subheader: string;
declare const text: string;

export {
	subheader,
	text
};

declare const __default_export__: {
	subheader: typeof subheader;
	text: typeof text;
};
export default __default_export__;
