/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const content: string;
declare const maxW: string;

export {
	content,
	maxW
};

declare const __default_export__: {
	content: typeof content;
	maxW: typeof maxW;
};
export default __default_export__;
