/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const header: string;
declare const title: string;

export {
	header,
	title
};

declare const __default_export__: {
	header: typeof header;
	title: typeof title;
};
export default __default_export__;
