/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const footer: string;
declare const container: string;
declare const links: string;
declare const link: string;
declare const text: string;

export {
	footer,
	container,
	links,
	link,
	text
};

declare const __default_export__: {
	footer: typeof footer;
	container: typeof container;
	links: typeof links;
	link: typeof link;
	text: typeof text;
};
export default __default_export__;
