/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const text: string;

export {
	text
};

declare const __default_export__: {
	text: typeof text;
};
export default __default_export__;
