/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const link: string;

export {
	link
};

declare const __default_export__: {
	link: typeof link;
};
export default __default_export__;
